# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/genutil/module/v1/module.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Module(betterproto.Message):
    """Module is the config object for the genutil module."""

    pass
