[tool.poetry]
name = "secret-sdk"
authors = ["SCRT LabRador, Secret analytics"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
description = "The Python SDK for Secret"
homepage = "https://github.com/stephanegg/secret-sdk-python"
keywords = ["jigu", "blockchain", "terra", "defi", "crypto"]
license = "MIT"
packages = [{ include = "secret_sdk" }]
readme = "README.md"
repository = "https://github.com/stephanegg/secret-sdk-python"
version = "1.0"

[tool.poetry.dependencies]
aiohttp = "^3.7.3"
attrs = "^20.3.0"
bech32 = "^1.2.0"
bip32utils = "^0.3.post4"
ecdsa = "^0.16.1"
mnemonic = "^0.19"
python = "^3.7"
wrapt = "^1.12.1"
nest-asyncio = "^1.5.1"
protobuf = "^3.17.3"
furl = "^2.1.3"
boltons = "^21.0.0"
miscreant = "^0.3.0"
black = { version = "^20.8b1", optional = true}
mypy = { version = "^0.900", optional = true}
Sphinx = { version = "^3.4.3", optional = true}
grpcio-tools = "^1.45.0"
grpclib = "^0.4.2"
betterproto = "2.0.0b4"


[tool.poetry.dev-dependencies]
coverage = "^5.3.1"
flake8 = "^3.8.4"
isort = "^5.7.0"
pip = "^21.0"
pytest = "^6.2.1"
pytest-cov = "^2.11.1"
pytest-mock = "^3.5.1"
pytest-runner = "^5.2"
pytest-sugar = "^0.9.4"
watchdog = "^1.0.2"
wheel = "^0.36.2"
sphinx-rtd-theme = "^0.5.1"
sphinx-autodoc-typehints = "^1.11.1"
sphinx-autobuild = "^2020.9.1"
uvloop = "^0.15.0"
aioresponses = "^0.7.2"
asynctest = "^0.13.0"

[tool.pytest.ini_options]
addopts = "-ra -q"
minversion = "6.0"

[tool.flake8]
max-line-length = 88
extend-ignore = "E203"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
