# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/reflection/v1/reflection.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto
import grpclib

from .google import protobuf


@dataclass
class FileDescriptorsRequest(betterproto.Message):
    """FileDescriptorsRequest is the Query/FileDescriptors request type."""

    pass


@dataclass
class FileDescriptorsResponse(betterproto.Message):
    """FileDescriptorsResponse is the Query/FileDescriptors response type."""

    # files is the file descriptors.
    files: List[protobuf.FileDescriptorProto] = betterproto.message_field(1)


class ReflectionServiceStub(betterproto.ServiceStub):
    """
    Package cosmos.reflection.v1 provides support for inspecting protobuf file
    descriptors.
    """

    async def file_descriptors(self) -> FileDescriptorsResponse:
        """
        FileDescriptors queries all the file descriptors in the app in order to
        enable easier generation of dynamic clients.
        """

        request = FileDescriptorsRequest()

        return await self._unary_unary(
            "/cosmos.reflection.v1.ReflectionService/FileDescriptors",
            request,
            FileDescriptorsResponse,
        )
