# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tendermint/statesync/types.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Message(betterproto.Message):
    snapshots_request: "SnapshotsRequest" = betterproto.message_field(1, group="sum")
    snapshots_response: "SnapshotsResponse" = betterproto.message_field(2, group="sum")
    chunk_request: "ChunkRequest" = betterproto.message_field(3, group="sum")
    chunk_response: "ChunkResponse" = betterproto.message_field(4, group="sum")


@dataclass(eq=False, repr=False)
class SnapshotsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class SnapshotsResponse(betterproto.Message):
    height: int = betterproto.uint64_field(1)
    format: int = betterproto.uint32_field(2)
    chunks: int = betterproto.uint32_field(3)
    hash: bytes = betterproto.bytes_field(4)
    metadata: bytes = betterproto.bytes_field(5)


@dataclass(eq=False, repr=False)
class ChunkRequest(betterproto.Message):
    height: int = betterproto.uint64_field(1)
    format: int = betterproto.uint32_field(2)
    index: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class ChunkResponse(betterproto.Message):
    height: int = betterproto.uint64_field(1)
    format: int = betterproto.uint32_field(2)
    index: int = betterproto.uint32_field(3)
    chunk: bytes = betterproto.bytes_field(4)
    missing: bool = betterproto.bool_field(5)
