# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/crypto/keyring/v1/record.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .cosmos.crypto.hd import v1
from .google import protobuf


@dataclass
class Record(betterproto.Message):
    """Record is used for representing a key in the keyring."""

    # name represents a name of Record
    name: str = betterproto.string_field(1)
    # pub_key represents a public key in any format
    pub_key: protobuf.Any = betterproto.message_field(2)
    # local stores the private key locally.
    local: "RecordLocal" = betterproto.message_field(3, group="item")
    # ledger stores the information about a Ledger key.
    ledger: "RecordLedger" = betterproto.message_field(4, group="item")
    # Multi does not store any other information.
    multi: "RecordMulti" = betterproto.message_field(5, group="item")
    # Offline does not store any other information.
    offline: "RecordOffline" = betterproto.message_field(6, group="item")


@dataclass
class RecordLocal(betterproto.Message):
    """Item is a keyring item stored in a keyring backend. Local item"""

    priv_key: protobuf.Any = betterproto.message_field(1)


@dataclass
class RecordLedger(betterproto.Message):
    """Ledger item"""

    path: v1.BIP44Params = betterproto.message_field(1)


@dataclass
class RecordMulti(betterproto.Message):
    """Multi item"""

    pass


@dataclass
class RecordOffline(betterproto.Message):
    """Offline item"""

    pass
