# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/crisis/v1beta1/tx.proto, cosmos/crisis/v1beta1/genesis.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Optional

import betterproto
import grpclib

from .cosmos.base import v1beta1


@dataclass
class MsgVerifyInvariant(betterproto.Message):
    """
    MsgVerifyInvariant represents a message to verify a particular invariance.
    """

    # sender is the account address of private key to send coins to fee collector
    # account.
    sender: str = betterproto.string_field(1)
    # name of the invariant module.
    invariant_module_name: str = betterproto.string_field(2)
    # invariant_route is the msg's invariant route.
    invariant_route: str = betterproto.string_field(3)


@dataclass
class MsgVerifyInvariantResponse(betterproto.Message):
    """
    MsgVerifyInvariantResponse defines the Msg/VerifyInvariant response type.
    """

    pass


@dataclass
class MsgUpdateParams(betterproto.Message):
    """
    MsgUpdateParams is the Msg/UpdateParams request type. Since: cosmos-sdk
    0.47
    """

    # authority is the address that controls the module (defaults to x/gov unless
    # overwritten).
    authority: str = betterproto.string_field(1)
    # constant_fee defines the x/crisis parameter.
    constant_fee: v1beta1.Coin = betterproto.message_field(2)


@dataclass
class MsgUpdateParamsResponse(betterproto.Message):
    """
    MsgUpdateParamsResponse defines the response structure for executing a
    MsgUpdateParams message. Since: cosmos-sdk 0.47
    """

    pass


@dataclass
class GenesisState(betterproto.Message):
    """GenesisState defines the crisis module's genesis state."""

    # constant_fee is the fee used to verify the invariant in the crisis module.
    constant_fee: v1beta1.Coin = betterproto.message_field(3)


class MsgStub(betterproto.ServiceStub):
    """Msg defines the bank Msg service."""

    async def verify_invariant(
        self,
        *,
        sender: str = "",
        invariant_module_name: str = "",
        invariant_route: str = "",
    ) -> MsgVerifyInvariantResponse:
        """
        VerifyInvariant defines a method to verify a particular invariant.
        """

        request = MsgVerifyInvariant()
        request.sender = sender
        request.invariant_module_name = invariant_module_name
        request.invariant_route = invariant_route

        return await self._unary_unary(
            "/cosmos.crisis.v1beta1.Msg/VerifyInvariant",
            request,
            MsgVerifyInvariantResponse,
        )

    async def update_params(
        self, *, authority: str = "", constant_fee: Optional[v1beta1.Coin] = None
    ) -> MsgUpdateParamsResponse:
        """
        UpdateParams defines a governance operation for updating the x/crisis
        module parameters. The authority is defined in the keeper. Since:
        cosmos-sdk 0.47
        """

        request = MsgUpdateParams()
        request.authority = authority
        if constant_fee is not None:
            request.constant_fee = constant_fee

        return await self._unary_unary(
            "/cosmos.crisis.v1beta1.Msg/UpdateParams",
            request,
            MsgUpdateParamsResponse,
        )
