# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/feegrant/module/v1/module.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Module(betterproto.Message):
    """Module is the config object of the feegrant module."""

    pass
