# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ibc/core/types/v1/genesis.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto

from .ibc.core.channel import v1
from .ibc.core.client import v1
from .ibc.core.connection import v1


@dataclass
class GenesisState(betterproto.Message):
    """GenesisState defines the ibc module's genesis state."""

    # ICS002 - Clients genesis state
    client_genesis: v1.GenesisState = betterproto.message_field(1)
    # ICS003 - Connections genesis state
    connection_genesis: v1.GenesisState = betterproto.message_field(2)
    # ICS004 - Channel genesis state
    channel_genesis: v1.GenesisState = betterproto.message_field(3)
