# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cosmos/vesting/module/v1/module.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Module(betterproto.Message):
    """Module is the config object of the vesting module."""

    pass
